### ISSUE TITLE
Problem setting OwnRecipes up with Portainer

### ISSUE THREAD

**Issue by Jan-NiklasB** [ownrecipes/OwnRecipes#73]
Hey,
I stumbled over your fork while surfing through the issues of open-eats..
I tried to setup ownRecipes on my server but I don't get it fully runnning.

(Since the start-up.py gave a corrupted .yml I tried to  recode the docker-compose.yml for Portainer on my own)
My setup looks as follows:

<details>
<summary>docker-compose.yml</summary>

```
version: '3.1'
services:
  db:
    image: mariadb:10.7.3
    volumes:
      - /opt/own-recipes/database:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 20
    environment:
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MYSQL_DATABASE}
    restart: always
      
  api:
    image: ownrecipes/ownrecipes-api
    command: /startup/prod-entrypoint.sh
    restart: always
    volumes:
      - /opt/own-recipes/static-files:/code/static-files
      - /opt/own-recipes/site-media:/code/site-media
    depends_on:
      db:
        condition: service_healthy
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - API_URL=${API_URL}
      - API_PORT=${API_PORT}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - DJANGO_DEBUG=${DJANGO_DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - NODE_URL=${NODE_URL}
      - HTTP_X_FORWARDED_PROTO=${HTTP_X_FORWARDED_PROTO}
      
  web:
    image: ownrecipes/ownrecipes-web
    volumes:
      - /opt/own-recipes/public-ui:/code/public-ui
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      #- REACT_APP_ADMIN_URL=${REACT_APP_ADMIN_URL}
      - REACT_APP_LOCALE=${REACT_APP_LOCALE}
      - REACT_APP_REQUIRE_LOGIN=${REACT_APP_REQUIRE_LOGIN}
      - REACT_APP_LEGAL_URL=${REACT_APP_LEGAL_URL}
      - REACT_APP_PRIVACY_URL=${REACT_APP_PRIVACY_URL}
    restart: on-failure
      
  nginx:
    image: ownrecipes/ownrecipes-nginx
    command: ./start.sh
    volumes:
      - /opt/own-recipes/static-files:/var/www/html/ownrecipes-static/static-files
      - /opt/own-recipes/site-media:/var/www/html/ownrecipes-static/site-media
      - /opt/own-recipes/public-ui:/var/www/html/ownrecipes-static/public-ui
    ports:
      - "348:80"
    depends_on:
      - api
      - web
    environment:
      - API_URL=${API_URL}
      - API_PORT=${API_PORT}

      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - NODE_URL=${NODE_URL}
      - HTTP_X_FORWARDED_PROTO=${HTTP_X_FORWARDED_PROTO}
    restart: always
```
</details>
<details>

<summary>env-variables</summary>

```
MYSQL_DATABASE=ownrecipes
MYSQL_ROOT_PASSWORD=*SECRET*
API_URL=0.0.0.0:8000
API_PORT=8000
DJANGO_SECRET_KEY=*SECRET*
DJANGO_SETTINGS_MODULE=base.settings
DJANGO_DEBUG=False
ALLOWED_HOST=localhost,127.0.0.1,eat.mydomain.tld
NODE_URL=https://eat.mydomain.tld:443
HTTP_X_FORWARDED_PROTO=true
REACT_APP_API_URL=https://eat.mydomain.tld
REACT_APP_ADMIN_URL=
REACT_APP_LOCALE=de
REACT_APP_REQUIRE_LOGIN=false
REACT_APP_LEGAL_URL=
REACT_APP_PRIVACY_URL=
```
</details>

<details>
<summary>Apache virtual server config</summary>

```
ServerName eat.mydomain.tld
LogLevel info
ErrorLog /var/log/www/eat.mydomain.tld_error.log
TransferLog /var/log/www/eat.mydomain.tld_access.log
RewriteEngine on
RewriteCond %{SERVER_NAME} =eat.mydomain.tld
ReWriteCond %{SERVER_PORT} !^443$
RequestHeader set "Host" "eat.mydomain.tld"
RequestHeader set "X-Forwarded-Proto" "https"
RequestHeader set "X-Forwarded-Port" 443
AllowEncodedSlashes On
ProxyPass "/" http://127.0.0.1:348/ retry=0 timeout=5 nocanon
ProxyPassReverse / http://127.0.0.1:348/ nocanon

ProxyPass "/api" http://127.0.0.1:348/api retry=0 timeout=5 nocanon
ProxyPassReverse /api http://127.0.0.1:348/api nocanon

ProxyPass "/admin" http://127.0.0.1:348/admin retry=0 timeout=5 nocanon
ProxyPassReverse /admin http://127.0.0.1:348/admin nocanon

LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\"" vhost_combined
LogFormat "%v %h %l %u %t \"%r\" %>s %b" vhost_common

SSLCertificateFile /etc/letsencrypt/live/eat.mydomain.tld/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/eat.mydomain.tld/privkey.pem
Include /etc/letsencrypt/options-ssl-apache.conf


Keepalive On
ProxyPreserveHost On
```
</details>

Using this the server starts, and operates as intended, but when calling the URL I get following errors and the whole recipe area is missing:

```
XHR GET https://eat.mydomain.tld/api/v1/recipe/mini-browse/?fields=id,slug,title,pub_date,rating,photo_thumbnail,info&limit=4 [HTTP/1.1 400 Bad Request 93ms]
XHR GET https://eat.mydomain.tld/api/v1/news/entry/ [HTTP/1.1 400 Bad Request 89ms]

```

Also /admin and /api gives my 400 Bad Request

Any Idea what I'm missing?
